// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"io/ioutil"
	"os"

	"github.com/swaggo/swag"
)

type s struct{}

func (s *s) ReadDoc() string {
	jsonFile, err := os.Open("docs/swagger.json")
	if err != nil {
		return ""
	}
	defer jsonFile.Close()

	byteValue, err := ioutil.ReadAll(jsonFile)
	if err != nil {
		return ""
	}

	return string(byteValue)
}

func init() {
	swag.Register(swag.Name, &s{})
}
